var iFileName = "LaserLlama - Compendium of Spells.js";
// Tested on sheet version 13.1.7
// Script updated to the LaserLlama GMBinder file https://www.gmbinder.com/share/-NQcEN32m0-1u_UMFV5h (Compendium of Spells) as of February 27th, 2025
RequiredSheetVersion("13.1.7");

var AtHigherLevels = "\n   " + toUni("At Higher Levels") + ": ";

// Cantrips

SpellsList["acid splash ll"] = {
	name : "Acid Splash LL",
	source : ["GMB:LL", 0],
	classes : ["artificer", "magus", "sorcerer", "wizard"],
	level : 0,
	school : "Evoc",
	time : "1 a",
	range : "60-ft",
	components : "V,S",
	duration : "Instantaneous",
	description : "dex save for all within 5ft of point in range. 1d6 acid damage on a fail; +1d6 at CL 5, 11, 17",
    descriptionCantripDie : "crea within 5 ft of point save or `CD`d6 Acid dmg",
	descriptionFull : "You hurl an orb of caustic acid at a point you can see within range. Creatures within 5 feet of that point must succeed on a Dexterity saving throw or take 1d6 acid damage.",
	},
 
SpellsList["beckon air ll"] = {
	name : "Beckon Air LL",
	source : ["GMB:LL", 0],
	classes : ["druid", "sorcerer"],
	level : 0,
	school : "Trans",
	time : "1 a",
	range : "60-ft",
	components : "V,S",
	duration : "Instantaneous",
	description : "Create small sensory effect in 5ft cube -or- hurl air at creature to force str save: 1d6 thunder damage on fail and pushed back 10ft if medium or smaller. +1d6 at CL 5, 11, 17",
    descriptionCantripDie : "`CD`d6 Thunder dmg and pushed 10ft if medium or smaller.",
	descriptionFull : "You can manipulate the winds and use them to assault foes. When you cast this spell choose one of the following effects:" + "\n " + "\u2022 Manipulate Air. You manipulate the air in a 5-foot cube within range, creating a small sensory affect such as causing leaves to rustle, shutters to slam shut, or clothing to ripple." + "\n " + "\u2022 Hurl Squall. You create a small wind squall in your hand and hurl it at a target you can see within range, forcing it to make a Strength saving throw. On a failed save, it takes 1d6 thunder damage and a Medium or smaller target is knocked back 10 feet in a straight line.",
	},
   
SpellsList["booming blade ll"] = {
	name : "Booming Blade LL",
	source : ["GMB:LL", 0],
	classes : ["artificer", "bard", "magus", "sorcerer", "warlock"],
	level : 0,
	school : "Evoc",
	time : "1 bns",
	range : "Self",
	components : "V,M",
    compMaterial : "a simple or martial melee weapon",
	duration : "1 rnd",
	description : "Attacks with my chosen melee deal thunder until beginning of next round. 1 target I hit takes 1d6 thunder damage if they willingly move 5ft.",
	descriptionCantripDie : "Melee wea atk with cast; if hit and if moves next round +`CD`d6 Thunder dmg",
	descriptionFull : "As a bonus action, you wreathe the melee weapon used in the casting of this spell with thunderous magic. Until the start of your next turn, your attacks with that weapon deal thunder damage in place of the weapon's normal damage type. Once per casting when you deal thunder damage with this spell, you can envelop your target in thunderous energy until the start of your next turn. If the target willingly moves 5 feet or more before then, this thunderous energy explodes and it takes 1d6 thunder damage, then the energy dissipates.",
	},
 
SpellsList["blade ward ll"] = {
    name : "Blade Ward LL",
    source : ["GMB:LL", 0],
    classes : ["bard", "magus", "psion","shaman","sorcerer","warlock", "wizard"],
    level : 0,
    school : "Abjur",
    time : "1 bns",
    range : "Self",
    components : "V,S",
    duration : "Conc, 1 min",
    description : "For the duration, reduce any bludgeoning, piercing and slashing damage by 1d4.",
    descriptionFull : "You trace a sigil of warding into the air. Whenever you take bludgeoning, piercing, or slashing damage for the duration of this spell, you can reduce the damage you would take by 1d4.",
},
 
SpellsList["contron flame ll"] = {
    name : "Control Flame LL",
    source : ["GMB:LL", 0],
    classes : ["druid", "sorcerer"],
    level : 0,
    school : "Trans",
    time : "1 a",
    range : "60-ft",
    components : "V,S",
    duration : "Instantaneous",
    description : "Manipulate flame within 5ft cube -or- hurl flame at creature. 1d8 fire damage on hit; +1d6 at CL 5, 11, 17",
    descriptionCantripDie : "`CD`d8 Fire dmg.",
    descriptionFull : "You can manipulate fire and use it to assault your foes. When you cast this spell choose one of the following effects:" + "\n " + "\u2022 Manipulate Fire. You choose nonmagical flame you can see within range and that fits within a 5-foot cube and cause the flame to grow to fill the cube, extinguish all flame within the cube, change its color, or cause simple animated shapes to appear within the flames, such as creatures or locations." + "\n " + "\u2022 Hurl Flame. You create a small ball of flickering flame in your hand and hurl it at one target that you can see within range, making a ranged spell attack against it. On hit, it takes 1d8 fire damage. Flammable objects that aren't being worn or carried are ignited when hit by this spell attack.",
},

SpellsList["friends ll"] = {
    name : "Friends LL",
    source : ["GMB:LL", 0],
    classes : ["bard", "psion", "sorcerer", "vessel", "wizard"],
    level : 0,
    school : "Ench",
    time : "1 a",
    range : "Self",
    components : "S,M",
    compMaterial : "a small amount of makeup applied to the face as this spell is cast",
    duration : "Conc, 1 min",
    description : "Cha save for 1 creature that can hear and see you. On fail: advantage with all Charisma checks targeting said creature for the duration.",
    descriptionFull : "You lace your words with soothing magic and force a creature of your choice that can hear and understand you to make a Wisdom saving throw. On a failure, you have advantage on all Charisma checks directed at that creature for the duration. On a successful save, the creature realizes that you used magic to attempt to influence it and becomes hostile toward you. A creature prone to violence might attack you, and other creatures might seek retribution against you in other ways.",
},
   
SpellsList["glitterbeam ll"] = {
    name : "Glitterbeam LL",
    source : ["GMB:LL", 0],
    classes : ["bard", "magus", "vessel"],
    level : 0,
    school : "Evoc",
    time : "1 a",
    range : "120-ft",
    components : "V,S",
    duration : "Instantaneous",
    description : "spell attack for 1d8 radiant damage. target must use action to remove glitter or suffer dis. on stealth and emits 5ft bright light; +1d8 at CL 5, 11, 17",
    descriptionCantripDie : "`CD`d8 Radiant dmg.",
    descriptionFull : "You project a beam of twinkling lights at a creature or object within range. Make a ranged spell attack against the target. On a hit, it takes 1d8 radiant damage. Until a creature uses an action to remove the glitter, a target hit by this spell emits bright light in a 5-foot radius and has disadvantage on any Dexterity (Stealth) checks it makes to hide or conceal itself.",
},
    
SpellsList["green-flame blade ll"] = {
    name : "Green-Flame Blade LL",
    source : ["GMB:LL", 0],
    classes : ["artificer", "magus", "sorcerer", "warlock"],
    level : 0,
    school : "Evoc",
    time : "1 bns",
    range : "Self",
    components : "V,M",
    compMaterial : "a simple or martial melee weapon",
    duration : "Instantaneous",
    description : "weapon deals fire damage. once per cast fire leaps to a 2nd target within 5ft of initial target, dealing 1d6 fire dmg; +1d6 at CL 5, 11, 17",
    descriptionCantripDie : "`CD`d6 fire dmg; ",
    descriptionFull : "As a bonus action, you wreathe the melee weapon used in the casting of this spell with emerald flames. Until the start of your next turn, your attacks with that weapon deal fire damage in place of the weapon's normal damage type. Once per casting when you deal fire damage with this spell, you can cause the flames to leap to another creature you can see within 5 feet of your target, dealing 1d6 fire damage to it.",
},
      
SpellsList["guidance ll"] = {
    name : "Guidance LL",
    source : ["GMB:LL", 0],
    classes : ["bard", "cleric", "druid", "psion", "shaman", "wizard"],
    level : 0,
    school : "Div",
    time : "1 a",
    range : "Touch",
    components : "V,S",
    duration : "Conc, 1 min",
    description : "1d4 to skill checks for the duration, 1d6 if you are proficient in the skill.",
    descriptionFull : "You touch another creature and infuse it with otherworldly knowledge of a skill of your choice. For the duration, it gains a 1d4 bonus to any ability checks it makes with that skill. If you are proficient in the skill, this bonus becomes 1d6.",
},
      
SpellsList["lightning lure ll"] = {
    name : "Lightning Lure LL",
    source : ["GMB:LL", 0],
    classes : ["artificer", "magus", "sorcerer", "warlock"],
    level : 0,
    school : "Evoc",
    time : "1 attack",
    range : "Self(15-ft)",
    components : "V",
    duration : "Instantaneous",
    description : "1 crea in range makes a str save. On fail, 1d8 lightning damage and pulled 5ft. +1d8 at CL 5, 11, 17",
    descriptionCantripDie : "`CD`d8 lightning dmg; pulled 5ft",
    descriptionFull : "You create a lash of arcane lightning and strikes at a creature of your choice you can see within 15 feet. It must succeed on a Strength saving throw or take 1d8 lightning damage and be pulled in a line to an unoccupied space within 5 feet of you.",
},
      
SpellsList["mind thrust ll"] = {
    name : "Mind Thrust LL",
    source : ["GMB:LL", 0],
    classes : ["psion"],
    level : 0,
    school : "Evoc",
    time : "1 attack",
    range : "120-ft",
    components : "V,S",
    duration : "Instantaneous",
    description : "spell attack. On hit, 1d10 psychic damage and cannot take reactions. +1d10 at CL 5, 11, 17",
    descriptionCantripDie : "`CD`d10 psychic dmg; cannot take reactions.",
    descriptionFull : "You assault the mind a creature within range with a torrent of psionic power. Make a ranged spell attack against the target. On hit, the creature takes 1d10 psychic damage and it cannot take reactions until the start of your next turn.",
},
       
SpellsList["mold earth ll"] = {
    name : "Mold Earth LL",
    source : ["GMB:LL", 0],
    classes : ["druid", "sorcerer"],
    level : 0,
    school : "Trans",
    time : "1 a",
    range : "60-ft",
    components : "V,S",
    duration : "Instantaneous",
    description : "Manipulate earth within a 5ft cube -or- spell attack: 1d6 bludgeoning damage on hit and knocked prone if small or smaller; +1d6 at CL 5, 11, 17",
    descriptionCantripDie : "`CD`d6 bludgenoning dmg; knocked prone if small or smaller.",
    descriptionFull : "You can manipulate the earth and use it to assault your foes. When you cast this spell choose one of the following effects:" + "\n " + "\u2022 Manipulate Earth. You manipulate loose earth and stone in a 5-foot cube within range, harmlessly excavating, moving, and depositing it up to 5 feet away, changing it into difficult terrain, or changing difficult terrain into normal terrain." + "\n " + "\u2022 Hurl Stone. You create a small ball of loose stone and dirt in your hand and hurl it at a target you can see within range, making a ranged spell attack against it. On hit, it takes your choice of either 1d6 bludgeoning or piercing damage, and if the target is Small or smaller it is knocked prone.",
},
      
SpellsList["mystic hammer ll"] = {
    name : "Mystic Hammer LL",
    source : ["GMB:LL", 0],
    classes : ["psion"],
    level : 0,
    school : "Trans",
    time : "1 a",
    range : "60-ft",
    components : "V,S",
    duration : "Instantaneous",
    description : "1 crea in range must Str save. On fail, 1d6 force damage and knocked prone. Large and Larger crea have adv. on save; +1d6 at CL 5, 11, 17",
    descriptionCantripDie : "`CD`d6 force dmg; knocked prone.",
    descriptionFull : "You batter a creature within range with psionic force, forcing it to make a Strength saving throw. On a failed save, it takes 1d6 force damage and it knocked prone. Large and larger creatures have advantage on this Strength saving throw.",
},
      
SpellsList["otherworldly grasp ll"] = {
    name : "Otherwordly Grasp LL",
    source : ["GMB:LL", 0],
    classes : ["shaman", "sorcerer", "vessel", "warlock", "wizard"],
    level : 0,
    school : "Necro",
    time : "1 a",
    range : "Self",
    components : "S,M",
    compMaterial : "an empty hand",
    duration : "Instantaneous",
    description : "spell attack 1 crea within melee range. On hit, 1d8 necrotic damage, gain half of damage as temp hp; +1d8 at CL 5, 11, 17",
    descriptionCantripDie : "`CD`d8 necrotic dmg; can gain half damage dealt as temp hp.",
    descriptionFull : "You channel necrotic spiritual power to your hand, changing it into a withered specter of itself. Make a melee spell attack against one creature within your reach. On hit, it takes 1d8 necrotic damage, and you can choose to gain temporary hit points equal to half the necrotic damage dealt.",
},

SpellsList["poison spray ll"] = {
    name : "Poison Spray LL",
    source : ["GMB:LL", 0],
    classes : ["artificer", "druid", "magus", "shaman", "sorcerer", "warlock", "wizard"],
    level : 0,
    school : "Necro",
    time : "1 a",
    range : "30-ft",
    components : "V,S",
    duration : "Instantaneous",
    description : "spell attack 1 crea within range. On hit, 1d12 poison damage; +1d12 at CL 5, 11, 17",
    descriptionCantripDie : "`CD`d12 poison dmg;",
    descriptionFull : "You raise your hand and project a toxic mist at a creature you can see within range. Make a ranged spell attack against the target. On hit, the target takes 1d12 poison damage.",
},

SpellsList["primal savagery ll"] = {
    name : "Primal Savagery LL",
    source : ["GMB:LL", 0],
    classes : ["druid", "shaman"],
    level : 0,
    school : "Trans",
    time : "1 attack",
    range : "Self",
    components : "S,M",
    compMaterial : "an empty hand",
    duration : "Instantaneous",
    description : "for 1 unarmed strike deal 1d6 + spell mod. magic piercing or slashing damage; lvl5:d8, lvl13:d10, lvl17:d12",
    descriptionFull : "As part of an unarmed strike, your fingers transform into savage claws, and you use your spellcasting modifier for the attack roll. On hit, this unarmed strike deals magical piercing or slashing damage equal to 1d6 + your spellcasting modifier. Your fingers revert to normal after this unarmed strike.",
},

SpellsList["psionic strike ll"] = {
    name : "Psionic Strike LL",
    source : ["GMB:LL", 0],
    classes : ["psion"],
    level : 0,
    school : "Evoc",
    time : "1 attack",
    range : "Self",
    components : "S,M",
    compMaterial : "an empty hand",
    duration : "Instantaneous",
    description : "for 1 unarmed strike deal 1d6 + spell mod. psychic damage; lvl5:d8, lvl13:d10, lvl17:d12",
    descriptionFull : "As part of an unarmed strike, you manifest a blade of psionic energy in your hand. On hit, the target takes psychic damage equal to 1d6 + your Strength modifier, in place of the normal damage of your unarmed strike. Your hand instantly reverts to its normal appearance after your attack.",
},

SpellsList["resistance ll"] = {
    name : "Resistance LL",
    source : ["GMB:LL", 0],
    classes : ["bard", "cleric", "druid", "wizard"],
    level : 0,
    school : "Abjur",
    time : "1 a",
    range : "Self",
    components : "V,S",
    duration : "Conc, 1 min",
    description : "once per turn for the duration, target adds 1d4 to forced saving throws.",
    descriptionFull : "You weave a protective mantle of magic around one willing creature you touch. Once per turn, when the target is forced to make a saving throw it can gain a 1d4 bonus to its roll.",
},

SpellsList["seance ll"] = {
    name : "Seance LL",
    source : ["GMB:LL", 0],
    classes : ["shaman"],
    level : 0,
    school : "Trans",
    time : "1 a",
    range : "30-ft",
    components : "V,S",
    duration : "1 action",
    description : "channel minor spirits to change the material world.",
    descriptionFull : "You channel minor spirits, allowing them to work through you so that they may once again affect change in the material world. You create one of the following effects within range:" + "\n " + "\u2022 You create an instantaneous, harmless sensory effect, such as a flickering azure flame, an unnaturally chill breeze, rhythmic chanting, or the smell of incense." + "\n " + "\u2022 A minor spirit briefly appears and fades away." + "\n " + "\u2022 You instantaneously light or snuff out a candle, torch, or a small campfire." + "\n " + "\u2022 A mote or iridescent light points to the closest place of spiritual power, recent death, or new birth." + "\n " + "\u2022 Ley lines within range briefly reveal themselves as they flicker with otherworldly light.",
},

SpellsList["shape water ll"] = {
    name : "Shape Water LL",
    source : ["GMB:LL", 0],
    classes : ["druid", "sorcerer"],
    level : 0,
    school : "Trans",
    time : "1 a",
    range : "60-ft",
    components : "V,S",
    duration : "Instantaneous",
    description : "manipulate water within a 5ft cube within range -or- hurl orb of water at 1 crea (dex save) for 1d8 cold damage; +1d8 at CL 5, 11, 17 ",
    descriptionCantripDie : "`CD`d8 cold dmg; extuingish flame within 5ft;",
    descriptionFull : "You can manipulate water and use it to assault your enemies. When you cast this spell choose one of the following effects:" + "\n " + "\u2022 Manipulate Water. You manipulate water in a 5-foot cube within range, harmlessly changing the direction it is flowing, altering its color or opacity, causing simple animated shapes to appear, or if there are no creatures in it you can freeze it." + "\n " + "\u2022 Hurl Wave. You create a small orb of tempestuous water in your hand and hurl it at one target you can see within range, forcing it to make a Dexterity saving throw. On a failed save, the target takes 1d8 cold damage, and any non-magical flame it is holding, or within 5 feet of it, is instantly extinguished.",
},

SpellsList["sword burst ll"] = {
    name : "Sword Burst LL",
    source : ["GMB:LL", 0],
    classes : ["magus", "psion", "warlock", "wizard"],
    level : 0,
    school : "Abjur",
    time : "1 a",
    range : "Self",
    components : "V,S",
    duration : "Instantaneous",
    description : "crea within 5ft make a dex save or 1d6 slashing damage; lvl5:d8, lvl13:d10, lvl17:d12",
    descriptionFull : "You conjure a defensive ring of spectral blades which sweep around you. Creatures within 5 feet of you must succeed on a Dexterity saving throw or take 1d6 slashing damage.",
},

SpellsList["tempestuous blade ll"] = {
    name : "Tempestuous Blade LL",
    source : ["GMB:LL", 0],
    classes : ["artificer", "magus", "warlock"],
    level : 0,
    school : "Evoc",
    time : "1 bns",
    range : "Self",
    components : "V,M",
    compMaterial : "a simple or martial melee weapon",
    duration : "1 round",
    description : "weapon deals lightning damage for 1 round. once per cast on hit infuse target with electricity, 1d6 lightning damage if target uses their reaction.",
    descriptionFull : "As a bonus action, you infuse the melee weapon used in the casting of this spell with electrified magic. Until the start of your next turn, your attacks with that weapon deal lightning damage in place of the weapon's normal damage type.:" + "\n " + " Once per casting when you deal lightning damage with this spell, you can infuse your target with an electrical charge until the start of your next turn. If the target uses a reaction of any kind before then, this tempestuous charge is unleashed and it takes 1d6 lightning damage.",
},

SpellsList["true strike ll"] = {
    name : "True Strike LL",
    source : ["GMB:LL", 0],
    classes : ["bard", "magus", "psion", "warlock", "wizard"],
    level : 0,
    school : "Div",
    time : "1 bns",
    range : "Self",
    components : "S,M",
    compMaterial : "a simple or martial melee weapon",
    duration : "Conc, 1 round",
    description : "add 1d4 to first hit roll against target before my next turn; lvl5:d6, lvl13:d8, lvl17:d10",
    descriptionFull : "You infuse your weapon with divination magic and point it at one creature you can see. The next time you make a melee attack with this weapon against that target before the start of your next turn, you add 1d4 to your attack roll.",
},

SpellsList["viscious mockery ll"] = {
    name : "Viscious Mockery LL",
    source : ["GMB:LL", 0],
    classes : ["bard"],
    level : 0,
    school : "Ench",
    time : "1 a",
    range : "30-ft",
    components : "V",
    duration : "Instantaneous",
    description : "1 target in range makes a wis save. On fail, take 1d6 psychic damage and dis. on atk rolls against anyone but you until start of your next turn; +1d6 at CL 5, 11, 17",
    descriptionCantripDie : "`CD`d6 psychic dmg;",
    descriptionFull : "You unleash a string of provoking words at a creature that can hear and understand you within range. The target must succeed on a Wisdom saving throw, or it takes 1d6 psychic damage and have disadvantage on every attack roll against targets other than you until the start of your next turn.",
},

// 1st level

SpellsList["arcane lance ll"] = {
    name : "Arcane Lance LL",
    source : ["GMB:LL", 0],
    classes : ["magus", "wizard"],
    level : 1,
    school : "Evoc",
    time : "1 a",
    range : "90-ft",
    components : "V,S,M",
    compMaterial : "a clear 1-inch crystal",
    duration : "Instantaneous",
    description : "spell attack. On hit, 5d4 force damage + 2d4/SL",
    descriptionFull : "You conjure a lance of pure arcane energy in your hand and make a ranged spell attack against a creature you can see within range. On hit, the target takes 5d4 force damage."+ AtHigherLevels +" When you cast this spell using a spell slot of 2nd-level or higher, the damage increases by 2d4 for each slot level above 1st.",
},

SpellsList["divine favor ll"] = {
    name : "Divine Favor LL",
    source : ["GMB:LL", 0],
    classes : ["paladin"],
    level : 1,
    school : "Evoc",
    time : "1 bns",
    range : "Self",
    components : "V,S",
    duration : "Conc, 1 min",
    description : "empower a weapon within 10 feet. Weapon deals 1d4 extra radiant damage on hit. +1 weapon/SL",
    descriptionFull : "Your prayer empowers one weapon of your choice within 10 feet of you with divine radiance. Until the spell ends, attacks with that weapon deal an extra 1d4 radiant damage on a hit."+ AtHigherLevels + "When you cast this spell using a spell slot of 2nd level or higher, you target one additional weapon within 10 feet of you for each slot level above 1st.",
},

SpellsList["ensnaring strike ll"] = {
    name : "Ensnaring Strike LL",
    source : ["GMB:LL", 0],
    classes : ["artificer", "ranger"],
    level : 1,
    school : "Conj",
    time : "on hit",
    range : "Self",
    components : "V,M",
    compMaterial : "a weapon worth at least 1 sp",
    duration : "Conc, 1 min",
    description : "on hit with a weapon attack: target must make a str save or be restrained. Large or larger creatures have adv. on the save. +1d6/SL",
    descriptionFull : "When you hit a creature with a weapon attack, you can cause the point of impact to explode with a writhing mass of thorny vines. The target must succeed on a Strength saving throw or be restrained by the vines until the spell ends. Creatures that are Large or larger have advantage on this saving throw. The restrained creature takes 1d6 piercing damage at the start of each of its turns." + "\n " + "\u2022 The restrained creature, or another creature within 5 feet, can use its action to make a Strength check against your Spell save DC, freeing it on a success. "+ AtHigherLevels + "When you cast this spell using a spell slot of 2nd-level or higher, the damage it takes at the start of each turn increases by 1d6 for each slot level above 1st.",
},

SpellsList["ethereal anchor ll"] = {
    name : "Ethereal Anchor LL",
    source : ["GMB:LL", 0],
    classes : ["paladin", "psion", "vessel"],
    level : 1,
    school : "Conj",
    time : "1 a",
    range : "60-ft",
    components : "V,S,M",
    compMaterial : "a silver nail",
    duration : "Conc, 1 min",
    description : "spell attack on 1 crea. On hit, 3d6 radiant damage and speed reduced to 0; +1d6/SL",
    descriptionFull : "You hurl a bolt of pure spirit at a creature within range. Make a ranged spell attack against your target. On hit, it takes 3d6 radiant damage and for the duration, its speed is reduced to 0 as it is pinned in place by the spiritual bolt. As an action, any creature can make a Strength ability check against your Spell save DC, ending this spell's effects on a success." + AtHigherLevels + "When you cast this spell using a spell slot of 2nd level or higher, the radiant damage increases by 1d6 for each slot level above 1st.",
},

SpellsList["ghastly flight ll"] = {
    name : "Ghastly Flight LL",
    source : ["GMB:LL", 0],
    classes : ["shaman", "warlock"],
    level : 1,
    school : "Conj",
    time : "1 a",
    range : "Self (60-ft line)",
    components : "V,S,M",
    compMaterial : "powdered remains of a creature",
    duration : "Instantaneous",
    description : "all within 60ft long, 5ft wide line must succeed on a con save. On fail, 2d8 and creature cannot regain hit points until start of your next turn. Half damage on save; +1d8/SL",
    descriptionFull : "You release a malevolent spirit that flies out from you in a direction of your choice in a 60-foot long, 5-foot wide line, at which point it fades away. Each creature within the line must make a Constitution saving throw. On a failed save, creatures take 2d8 necrotic damage and cannot regain hit points until the start of your next turn. On a success, creatures take half as much damage and can regain hit points as normal." + AtHigherLevels + "When you cast this spell using a spell slot of 2nd-level or higher, the damage increases by 1d8 for each slot level above 1st.",
},

SpellsList["hail of thorns ll"] = {
    name : "Hail of Thorns LL",
    source : ["GMB:LL", 0],
    classes : ["ranger"],
    level : 1,
    school : "Conj",
    time : "on hit",
    range : "60-ft",
    components : "V",
    duration : "Instantaneous",
    description : "on ranged weapon attack hit, each crea within 5ft of target must make a dex save or take 1d10 piercing damage. half damage on success; +1d10/SL",
    descriptionFull : "When you hit a creature within range with a ranged weapon attack, you can cause the piece of ammunition to explode into a hail of thorns. In addition to the normal effect of the attack, the target of your attack and each creature within 5 feet must make a Dexterity saving throw. Creatures take 1d10 piercing damage on a failure, or half as much damage on a success." + AtHigherLevels + "When you cast this spell using a spell slot of 2nd-level or higher, the damage increases by 1d10 for each slot level above 1st.",
},

SpellsList["id insinuation ll"] = {
    name : "Id Insinuation LL",
    source : ["GMB:LL", 0],
    classes : ["psion"],
    level : 1,
    school : "Ench",
    time : "1 a",
    range : "60-ft",
    components : "V,S",
    duration : "Conc, 1 min",
    description : "force wis save on 1 crea within range. on fail, crea is incapacitated for the duration; +1 crea/SL within 30ft of one another",
    descriptionFull : "You unleash a storm of conflicting desires within the mind of one creature you can see within range. It must succeed on a Wisdom saving throw or be incapacitated for the duration." + "\n " + "\u2022 The creature can repeat this Wisdom saving throw at the end of each of its turns and each time that it takes damage, ending the effects of this spell on a successful save." + AtHigherLevels + "When you cast this spell using a spell slot of 2nd level or higher, you can target one additional creature for each slot level above 1st. The creatures must be within 30 feet of each other when you target them",
},

SpellsList["jump ll"] = {
    name : "Jump LL",
    source : ["GMB:LL", 0],
    classes : ["artificer", "druid", "magus", "psion", "ranger", "sorcerer", "vessel", "warlock", "wizard"],
    level : 1,
    school : "Trans",
    time : "1 bns",
    range : "Touch",
    components : "V,S,M",
    compMaterial : "a grasshopper's hind leg",
    duration : "1 min",
    description : "once per turn, target can spend 10ft of movement to jump 30ft",
    descriptionFull : "You touch a willing creature and greatly alter its buoyancy. Once on each of its turns until the spell ends, the target can spend 10 feet of its movement to jump up to 30 feet." + AtHigherLevels + "When you cast this spell using a spell slot of 2nd-level or higher, the distance of this magical jump increases by 10 feet for each slot level above 1st.",
},

SpellsList["searing smite ll"] = {
    name : "Searing Smite LL",
    source : ["GMB:LL", 0],
    classes : ["paladin"],
    level : 1,
    school : "Evoc",
    time : "on hit",
    range : "Self",
    components : "V,M",
    compMaterial : "a melee weapon worth at least 1 sp",
    duration : "Instantaneous",
    description : "deal 1d8 bonus fire damage and target ignites; target must succeed on con save each turn or take 1d8 fire damage; +1d8/SL",
    descriptionFull : "When you hit with a melee weapon attack you can cause the weapon to ignite with white-hot intensity. This attack deals 1d8 additional fire damage and the target bursts into flames. At the start of each of its turns, it must make a Constitution saving throw. On a failed save, it takes 1d8 fire damage, but on a success, the flames are extinguished. Another creature can use an action to extinguish these magical flames. " + "\n " + "\u2022 If your target is a plant, both the initial fire damage and the fire damage dealt on a failed saving throw increase by 1d8." + AtHigherLevels + "When you cast this spell using a spell slot of 2nd-level or higher, both the initial fire damage dealt by the attack and the fire damage dealt to the creature on a failed saving throw increase by 1d8 for each slot.",
},

SpellsList["shield ll"] = {
    name : "Shield LL",
    source : ["GMB:LL", 0],
    classes : ["magus", "psion", "sorcerer", "wizard"],
    level : 1,
    school : "Abjur",
    time : "reaction, when hit or targeted by magic missile",
    range : "Self",
    components : "V,S",
    duration : "Instantaneous",
    description : "until end of current turn, bonus AC equal to 1 + spell mod. and immune to magic missile.",
    descriptionFull : "A shimmering barrier of magical force appears to protect you. Until the end of the current turn, you gain a bonus to your Armor Class equal to 1 + your Spellcasting modifier and you take no damage from the magic missile spell." + AtHigherLevels + "When you cast this spell using a spell slot of 2nd-level or higher, the bonus to your Armor Class increases by 1 for each slot level above 1st.",
},

SpellsList["thunderous smite ll"] = {
    name : "Thunderous Smite LL",
    source : ["GMB:LL", 0],
    classes : ["bard", "paladin"],
    level : 1,
    school : "Evoc",
    time : "on hit",
    range : "Self",
    components : "V,M",
    compMaterial : "a melee weapon worth at least 1 sp",
    duration : "Instantaneous",
    description : "attack deals 1d8 bonus thunder damage. Target must succeed str save or be pushed 10ft and knocked prone; +1d8 & 10ft/SL",
    descriptionFull : "When you hit with a melee weapon attack, you can cause the weapon to explode with a thunderous shockwave audible out to 300 feet. This attack deals 1d8 additional thunder damage, and the target must succeed on a Strength saving throw or be pushed 10 feet away from you in a line and fall prone. Huge and larger targets have advantage on this saving throw." + "\n " + "\u2022 If your target is a construct or an earth elemental the bonus thunder damage increases by 1d8 and it has disadvantage on the Strength saving throw." + AtHigherLevels + "When you cast this spell using a spell slot of 2nd-level or higher, the thunder damage increases by 1d8, and the target is pushed an additional 10 feet away from you in a straight line for each spell slot level above 1st.",
},

SpellsList["torrent ll"] = {
    name : "Torrent LL",
    source : ["GMB:LL", 0],
    classes : ["druid", "magus", "sorcerer", "wizard"],
    level : 1,
    school : "Evoc",
    time : "1 a",
    range : "Self (30-ft line)",
    components : "V,S,M",
    compMaterial : "a mirror",
    duration : "Instantaneous",
    description : "str save for all crea in line. on fail, take 1d12 cold damage and knocked back 10ft and land prone. Half damage on success; +1d12 & 10ft/SL",
    descriptionFull : "A burst of elemental water erupts from you in a line 30 feet long and 5 feet wide in a direction you choose, forcing any creature in that area to make a Strength saving throw. On a failure, it takes 1d12 cold damage and is knocked back 10 feet in a straight line and falls prone. On a success, it takes half as much damage and is not moved or knocked prone. A Huge or larger creature has advantage on its saving throw." + AtHigherLevels + "When you cast this spell using a spell slot of 2nd-level or higher, the damage increases by 1d12 and it knocks back 10 additional feet for each slot level above 1st.",
},

SpellsList["witch bolt ll"] = {
    name : "Witch Bolt LL",
    source : ["GMB:LL", 0],
    classes : ["artificer", "magus", "shaman", "sorcerer", "vessel", "warlock", "wizard"],
    level : 1,
    school : "Conj",
    time : "1 a",
    range : "30-ft",
    components : "V,S,M",
    compMaterial : "a piece of wood struck by lightning",
    duration : "Conc, 1 min",
    description : "spell attack. On hit target takes 1d12 lightning damage, target and you cannot move more than 30ft from another.",
    descriptionFull : "A beam of crackling energy lances out toward a creature within range, forming a sustained arc of lightning between you and the target. Make a ranged spell attack against that creature. On a hit, the target takes 1d12 lightning damage, and neither you nor the target can move more than 30 feet away from each other while this spell lasts." + "\n " + "\u2022 You can use an action on each subsequent turn to deal an additional 1d12 lighting damage to the creature. A creature can attempt to move beyond the range of the spell by using its action to make a Strength check against your Spell save DC. If another creature attempts to move the target of this spell beyond the range of this spell it can use its action to make a Strength check against your Spell save DC. Any attempts by the target or another creature (magical or mundane) to move the target beyond this range automatically fail." + "\n " + "\u2022 The spell immediately ends if you are forced to move more than 30 feet away from the target of this spell." + AtHigherLevels + "When you cast this spell using a spell slot of 2nd level or higher, both the initial and subsequent damage increases by 1d12 for each slot level above 1st.",
},

SpellsList["wrathful smite ll"] = {
    name : "Wrathful Smite LL",
    source : ["GMB:LL", 0],
    classes : ["paladin"],
    level : 1,
    school : "Evoc",
    time : "on hit",
    range : "Self",
    components : "V,M",
    compMaterial : "a melee weapon worth at least 1 sp",
    duration : "Conc, 1 min",
    description : "on hit with melee weapon, 1d8 additional psychic damage and target is frightened on failing a wis save; +1d8/SL",
    descriptionFull : "When you hit with a melee weapon attack you can cause the weapon to strike at both body and mind. This attack deals an additional 1d8 psychic damage, and the target must succeed on a Wisdom saving throw, or it is frightened of you until the spell ends. As an action, the creature can repeat this Wisdom saving throw, ending the effects of the spell on a success." + "\n " + "\u2022 If your target is an aberration or it can speak telepathically this bonus psychic damage increases by 1d8." + AtHigherLevels + "When you cast this spell using a spell slot of 2nd-level or higher, the psychic damage increases by 1d8 for each spell slot level above 1st.",
},

// 2nd level

SpellsList["aura of frost ll"] = {
    name : "Aura of Frost LL",
    source : ["GMB:LL", 0],
    classes : ["druid", "magus", "sorcerer"],
    level : 2,
    school : "Conj",
    time : "1 a",
    range : "Self (10-ft radius)",
    components : "V",
    duration : "Conc, 1 min",
    description : "surround yourself with 10ft frost aura. Creatures that enter it or start in it must make a con save or take 2d8 cold damage and have -20ft movement; +1d8 & -10ft/SL",
    descriptionFull : "Arcane frost, snow, and wind swirl about you in an aura with a 10-foot radius, and until the spell ends, the aura moves with you, centered on you. When a creature other than you, enters the area for the first time on a turn or starts its turn there, it must succeed on a Constitution saving throw or it takes 2d8 cold damage and have its speed is reduced by 20 feet until the start of its next turn. On a successful save, it takes half as much cold damage and its speed isn't reduced." + AtHigherLevels + "When you cast this spell using a spell slot of 3rd-level or higher, a creature that fails its save takes an additional 1d8 cold damage and has its speed reduced by an additional 10 feet for each spell level above 2nd.",
},

SpellsList["branding smite ll"] = {
    name : "Branding Smite LL",
    source : ["GMB:LL", 0],
    classes : ["paladin"],
    level : 2,
    school : "Evoc",
    time : "1 a",
    range : "Self (10-ft radius)",
    components : "V,M",
    compMaterial : "a melee weapon worth at least 1 sp",
    duration : "Conc, 1 min",
    description : "on hit with melee weapon, attack deals 2d8 bonus radiant damage, target sheds dim light and becomes visible; +1d8/SL",
    descriptionFull : "When you hit with a melee weapon attack you can cause the weapon to gleam with an otherworldly astral radiance. This attack deals 2d8 bonus radiant damage, and the target sheds dim light out to a 5-foot radius until the spell ends. The target also becomes visible if it was invisible and it cannot become invisible by magical or mundane means for the duration." + "\n " + "\u2022 If your target is a fiend or undead, or if it has the sunlight sensitivity trait, the bonus radiant damage increases by 1d8." + AtHigherLevels + "When you cast this spell using a spell slot of 3rd-level or higher, the radiant damage increases by 1d8 for each spell slot level above 2nd.",
},

SpellsList["cordon of arrows ll"] = {
    name : "Cordon of Arrows LL",
    source : ["GMB:LL", 0],
    classes : ["artificer", "ranger"],
    level : 2,
    school : "Trans",
    time : "1 a",
    range : "5-ft",
    components : "V,S,M",
    compMaterial : "three or more arrows or bolts",
    duration : "8 hours",
    description : "First crea that enters within 30ft of area makes dex save. On fail, 3d6 piercing damage. half damage on success; +2d6/SL",
    descriptionFull : "You plant three pieces of ranged weapon ammunition in the ground within range and transmute them to protect the area. The first creature to move within 30 feet of this enchanted ammunition must make a Dexterity saving throw. The target takes 3d6 piercing damage on a failed save, and half as much piercing damage on a successful save." + "\n " + "\u2022 As part of casting this spell, you can designate any number of creatures you choose, and the spell ignores them." + AtHigherLevels + "When you cast this spell using a spell slot of 3rd-level or higher, the amount of ammunition that can be transmuted increases by two for each slot level above 2nd. For each additional piece of ammunition you transmute with this spell, the damage increases by 1d6.",
},

SpellsList["elemental blade ll"] = {
    name : "Elemental Blade LL",
    source : ["GMB:LL", 0],
    classes : ["druid", "magus", "sorcerer"],
    level : 2,
    school : "Conj",
    time : "1 bns",
    range : "Self",
    components : "V,S,M",
    compMaterial : "a charred wooden hilt",
    duration : "Conc, 10 min",
    description : "summon blade and decide damage type (acid, cold, fire, poison, lightning or thunder). On hit with blade deal 2d6+spell mod. damage in chosen element; +1d6/2SLs",
    descriptionFull : "You evoke an elemental blade in a free hand, choosing one of the following damage types: acid, cold, fire, lightning, poison, or thunder. The elemental blade appears as if it were made of the chosen element, and lasts for the duration. If you let go of the blade, it disappears, but you can evoke the blade again as a bonus action without expending a spell slot." + "\n " + "\u2022 Whenever you would make a melee attack, you can make a melee spell attack with the elemental blade against a target within your reach. On hit, it takes damage of the chosen type equal to 2d6 + your spellcasting modifier." + "\n " + "\u2022 While in your hand, the blade sheds bright light in a 10-foot radius and dim light an additional 10 feet beyond that." + AtHigherLevels + "When you cast this spell using a spell slot of 4th level or higher, the damage increases by 1d6 for every two slot levels above 2nd.",
},

SpellsList["find steed ll"] = {
    name : "Find Steed LL",
    source : ["GMB:LL", 0],
    classes : ["paladin"],
    level : 2,
    school : "Conj",
    time : "1 min",
    range : "30-ft",
    components : "V,S",
    duration : "Instantaneous",
    description : "Summon CR 1/2 or lower, medium or large, quadruped as mount. It's int becomes 6 if otherwise lower.",
    descriptionFull : "You conjure a spirit in an unoccupied space within range that assumes the form of a supernaturally intelligent, strong, and loyal steed, which is instantly bonded to you. The Steed takes on the form of a Medium or Large quadrupedal beast that you have seen before with a CR of 1/2 or lower that does not have a climbing, flying, or swimming speed. Examples include: elk, camel, giant goat, mastiff, pony, or warhorse." + "\n " + "\u2022 Your Steed uses the stat block of the form chosen for it, but its creature type now reflects your alignment: celestial (good), fey (neutral), or fiend (evil). The Steed's Intelligence becomes 6 if it was lower, and it understands one language you speak." + "\n " + "\u2022 In combat, the Steed shares your initiative and acts during your turn. You control the Steed and choose how it acts, both in and out of combat. While mounted on it, you can make any spell you cast that targets only you also target your steed." + "\n " + "\u2022 While you and your Steed are within 1 mile of one another, you can use a special form of telepathy to communicate." + "\n " + "\u2022 If your Steed is reduced to 0 hit points it disappears. You can also use a bonus action to dismiss your Steed, causing it to disappear. Should you cast this spell again you can choose to either conjure the same Steed, and it reappears in range at its maximum hit points, or to conjure a new Steed, releasing your previous Steed from its bond in the process." + AtHigherLevels + "When you cast this spell using a spell slot of 4th-level or higher, your Steed can take on the form of any Medium or Large quadrupedal or winged beast, celestial, or monstrosity that you have seen before that has a CR of 2 or lower. Examples include: dire wolf, griffon, pegasus, peryton, polar bear, or rhinoceros.",
},

SpellsList["flame whip ll"] = {
    name : "Flame Whip LL",
    source : ["GMB:LL", 0],
    classes : ["druid", "vessel", "warlock"],
    level : 2,
    school : "Evoc",
    time : "1 attack",
    range : "Self",
    components : "V,S,M",
    compMaterial : "a charred wooden hilt",
    duration : "Conc, 10 min",
    description : "Summon a whip in place of an attack that deals 1d10+SpellMod fire damage. Choose to instantly grapple a hit creature. Can't attack while grappling a creature; +1d10/2SLs",
    descriptionFull : "In place of an attack, you can evoke a whip of pure flame in a free hand, that lasts for the duration. If you let go of the whip, it disappears, but you can evoke this Flame Whip again in place of another attack without expending a spell slot." + "\n " + "\u2022 Whenever you could make an attack, you can instead make a melee spell attack with your Flame Whip against one target within 10 feet that you can see. On hit, it takes fire damage equal to 1d10 + your spellcasting modifier, and if the target is Large or smaller you can instantly grapple it with the Whip." + "\n " + "\u2022 You cannot attack with the Whip while it is grappling a creature, but a grappled creature takes 1d10 fire damage at the start of its turn and can use its action to make a Strength check against your spell save DC, escaping on a success." + "\n " + "\u2022 While in your hand, your Flame Whip sheds bright light in a 10-foot radius and dim light for an additional 10 feet." + AtHigherLevels + "When you cast this spell using a spell slot of 4th level or higher, both instances of fire damage dealt increase by 1d10 for every two slot levels above 2nd.",
},

SpellsList["locate creature ll"] = {
    name : "Locate Creature LL",
    source : ["GMB:LL", 0],
    classes : ["bard", "cleric", "druid", "paladin", "psion", "ranger", "shaman", "wizard"],
    level : 2,
    school : "Div",
    time : "1 a",
    range : "Self",
    components : "V,S,M",
    compMaterial : "a magnet dipped in holy water",
    duration : "Conc, 1 hour",
    description : "Summon a whip in place of an attack that deals 1d10+SpellMod fire damage. Choose to instantly grapple a hit creature. Can't attack while grappling a creature; +1d10/2SLs",
    descriptionFull : "Describe or name a specific kind of beast or plant. It can be a specific creature known to you, or the nearest creature of a specific kind (such as a bear, oak, or horse), so long as you have seen such a creature within 30 feet at least once." + "\n " + "\u2022 If one is within 1 mile, the material component of this spell points to it as if it were a compass. If the target is in motion, it points to it for as long as it remains in range. If the creature is in a different form, such as under the effect of the polymorph spell, this spell doesn't locate the creature." + "\n " + "\u2022 This spell can't locate its target if any thickness of lead or 10 feet of running water blocks a straight line to the target." + AtHigherLevels + "When you cast this spell using a spell slot of 3rd-level or higher, the range and the type of creature you can locate increases: 3rd - 2 miles - Dragon, Giant, Humanoid, Monstrosity, Ooze. 4th - 3 miles Aberration, Construct, Undead. 5th - 5 miles - Celestial, Elemental, Fey, Fiend.",
},

SpellsList["lock/unlock ll"] = {
    name : "Lock/Unlock LL",
    source : ["GMB:LL", 0],
    classes : ["artificer", "wizard"],
    level : 2,
    school : "Abjur",
    time : "1 a",
    range : "Touch",
    components : "V,S,M",
    compMaterial : "a piton, which the spell consumes",
    duration : "Instantaneous",
    description : "Magically lock an object, assigning creatures that can bypass it or assigning a password -or- unlock a mundane lock.",
    descriptionFull : "You touch one closed door, window, gate, chest, or another entryway, and either lock or unlock it, using the rules below:" + "\n " + "\u2022 Lock. You and the creatures you designate when you cast this spell can open the object normally. You can also choose a password that, when spoken aloud within 5 feet of the object, suppresses the spell for 1 minute. This lock can be bypassed by a successful Strength check or thieves' tools check against your Spell save DC, at which point the spell is dispelled." + "\n " + "\u2022 Unlock. If the object is held shut by a mundane lock or it is stuck or barred, it is instantly unlocked, unstuck, or unbarred. If the object has multiple locks, only one of them is unlocked. Regardless, when you cast the spell, a loud knock, audible out to 300 feet, emanates from the target object.",
},

SpellsList["magic weapon ll"] = {
    name : "Magic Weapon LL",
    source : ["GMB:LL", 0],
    classes : ["artificer", "druid", "paladin", "magus", "ranger", "sorcerer", "wizard"],
    level : 2,
    school : "Trans",
    time : "1 bns",
    range : "Touch",
    components : "V,S",
    duration : "1 hour",
    description : "Touch a nonmagical weapon, it becomes a magical +1 for the duration; +2 with 3th lvl slot, +3 with 6th lvl slot",
    descriptionFull : "You touch a nonmagical weapon and imbue it with arcane power. For the duration, it becomes a magical weapon with a +1 bonus to attack and damage rolls." + AtHigherLevels + "When you cast this spell using a spell slot of 3rd-level or higher, the bonus is +2. When you use a spell slot of 6th-level or higher, the bonus increases to +3.",
},

SpellsList["totemic cowl ll"] = {
    name : "Totemic Cowl LL",
    source : ["GMB:LL", 0],
    classes : ["shaman"],
    level : 2,
    school : "Abjur",
    time : "1 a",
    range : "Touch",
    components : "V,S,M",
    compMaterial : "a leaf from the first day of fall",
    duration : "1 hour",
    description : "reduce any damage taken by 2; +1 damage reduced/SL",
    descriptionFull : "You touch a willing creature. Until the spell ends, it is cloaked in a ghostly cowl, and any damage it takes is reduced by 2." + AtHigherLevels + "When you cast this spell using a spell slot of 3rd-level or higher, the damage reduction from the cowl increases by 1 for each slot level above 2nd.",
},

SpellsList["mystic spear ll"] = {
    name : "Mystic Spear LL",
    source : ["GMB:LL", 0],
    classes : ["psion", "warlock"],
    level : 2,
    school : "Ench",
    time : "1 a",
    range : "120-ft",
    components : "V",
    duration : "Instantaneous",
    description : "force int save on crea in range. 4d6 psychic damage + incapacitated until start of my next turn on fail. half damage on success",
    descriptionFull : "You project a violent bolt of mental power at a creature you can see within range. You do not need to see the target if you speak its name as part of the verbal component of this spell." + "\n " + "\u2022 The creature must make an Intelligence saving throw. On a failed save, it takes 4d6 psychic damage and is incapacitated until the start of your next turn. On a successful save, it takes half as much psychic damage and is not incapacitated." + AtHigherLevels + "When you cast this spell using a spell slot of 3rd level or higher, the damage increases by 1d6 for each slot level above 2nd.",
},

SpellsList["mystic spear ll"] = {
    name : "Mystic Spear LL",
    source : ["GMB:LL", 0],
    classes : ["psion", "warlock"],
    level : 2,
    school : "Ench",
    time : "1 a",
    range : "120-ft",
    components : "V",
    duration : "Instantaneous",
    description : "reduce any damage taken by 2; +1 damage reduced/SL",
    descriptionFull : "You project a violent bolt of mental power at a creature you can see within range. You do not need to see the target if you speak its name as part of the verbal component of this spell." + "\n " + "\u2022 The creature must make an Intelligence saving throw. On a failed save, it takes 4d6 psychic damage and is incapacitated until the start of your next turn. On a successful save, it takes half as much psychic damage and is not incapacitated." + AtHigherLevels + "When you cast this spell using a spell slot of 3rd level or higher, the damage increases by 1d6 for each slot level above 2nd.",
},

SpellsList["pass without trace ll"] = {
    name : "Pass Without Trace LL",
    source : ["GMB:LL", 0],
    classes : ["druid", "ranger", "shaman"],
    level : 2,
    school : "Abjur",
    time : "1 a",
    range : "Self",
    components : "V,S,M",
    compMaterial : "Ashes from a burned leaf of mistletoe",
    duration : "Conc, 1 hour",
    description : "crea of my choice within 30ft add my spell mod to stealth checks and are lightly obscured.",
    descriptionFull : "A veil of shadows and silence radiates from you, masking you and your companions from detection. For the duration, you and creatures of your choice within 30 feet are considered to be lightly obscured and gain a bonus to all Dexterity (Stealth) checks equal to your Spellcasting modifier. Creatures under the effect of this spell leave no track or trace of their passing.",
},

SpellsList["restoration ll"] = {
    name : "Restoration LL",
    source : ["GMB:LL", 0],
    classes : ["artificer", "bard", "cleric", "druid", "paladin", "ranger"],
    level : 2,
    school : "Abjur",
    time : "1 a",
    range : "Touch",
    components : "V,S",
    duration : "Instantaneous",
    description : "touch a creature to end blinded, deafened, frightened, paralyzed or poisoned.",
    descriptionFull : "You touch a willing creature and instantly end one disease or one of the following conditions currently afflicting it: blinded, deafened, frightened, paralyzed, or poisoned." + AtHigherLevels + "When you cast this spell using a spell slot of 3rd-level or higher, the conditions and effects you can end increase, but the spell requires you to expend diamond dust of a certain value, which is consumed during casting: 3rd level -  10gp - charmed, 1 lvl exhaustion, 4th - 50gp - reduction to one stat or max hp, 5th - 100gp - petrified, one curse, or attunement to cursed item.",
},

// 3rd level

SpellsList["blinding smite ll"] = {
    name : "Blinding Smite LL",
    source : ["GMB:LL", 0],
    classes : ["paladin"],
    level : 3,
    school : "Evoc",
    time : "on hit",
    range : "Self",
    components : "V,M",
    compMaterial : "a melee weapon worth at least 1 sp",
    duration : "Conc, 1 min",
    description : "on hit, attack deals 3d8 bonus radiant damage, target must succeed on con save or be blinded for the duration.",
    descriptionFull : "When you hit with a melee weapon attack you can cause the weapon to flare with an overwhelming blinding light. This attack deals 3d8 bonus radiant damage, and the target must succeed on a Constitution saving throw or become blinded until the spell ends. The target can repeat this saving throw at the end of each of its turns, ending the effect on a success." + "\n " + "\u2022 If your target is a fiend or undead, or if it has the sunlight sensitivity trait, the bonus radiant damage increases by 1d8." + AtHigherLevels + "When you cast this spell using a spell slot of 3rd-level or higher, the radiant damage increases by 1d8 for each spell slot level above 2nd.",
},

SpellsList["cerebral blast ll"] = {
    name : "Cerebral Blast LL",
    source : ["GMB:LL", 0],
    classes : ["psion"],
    level : 3,
    school : "Evoc",
    time : "1 a",
    range : "Self(30-ft cone)",
    components : "V",
    duration : "Instantaneous",
    description : "creatures in area must make str save. On fail, 5d8 psychic damage and pushed 20ft and falls prone. half damage and not pushed/prone on save.",
    descriptionFull : "Your mind unleashes a blast of overwhelming mental force in a 30-foot cone. Creature in the area of this spell must make a Strength saving throw. On a failed save, a creature takes 5d8 psychic damage and is pushed 20 feet directly away from you in a line, then falls prone. On a success, creatures take half as much damage, remain in place, and don't fall prone." + AtHigherLevels + "When you cast this spell using a spell slot of 4th-level or higher, the psychic damage increases by 1d8 for each spell slot level above 3rd.",
},

SpellsList["conjure volley ll"] = {
    name : "Conjure Volley LL",
    source : ["GMB:LL", 0],
    classes : ["ranger"],
    level : 3,
    school : "Conj",
    time : "1 a",
    range : "Self",
    components : "V,S,M",
    compMaterial : "a single piece of ammunition and a ranged weapon, or one thrown weapon, all nonmagical",
    duration : "Instantaneous",
    description : "choose a point within 60ft and shoot exploding ammo in a 30ft radius, 20ft high cylinder. creatures must make a dex save or take 6d8 weapon damage on fail. half damage on save.",
    descriptionFull : "You fire one piece of nonmagical ammunition from a ranged weapon or throw a nonmagical thrown weapon into the air and choose a point within 60 feet." + "\n " + "\u2022 The ammunition or weapon explodes into a multitude of exact copies of it, which fall in a 30-foot-radius, 20-foot-high cylinder centered on the point you chose. Creatures within that area must make a Dexterity saving throw. They take 6d8 damage of the weapon's type on a failure, and half as much on a success. The ammunition or weapons created by this spell disintegrate once the effects of this spell are resolved." + AtHigherLevels + "When you cast this spell using a spell slot of 4th-level or higher, the damage of this spell increases by 1d8, and the radius of the cylinder increases by 5 feet for each slot level above 3rd.",
},

SpellsList["counterspell ll"] = {
    name : "Counterspell LL",
    source : ["GMB:LL", 0],
    classes : ["magus", "sorcerer", "warlock", "wizard"],
    level : 3,
    school : "Abjur",
    time : "1 reaction",
    range : "60-ft",
    components : "V,S",
    duration : "Instantaneous",
    description : "target and I both make an ability check, adding our SL. If I know or have target's spell prepared I have adv. If my roll is higher, spell is canceled.",
    descriptionFull : "You attempt to interrupt a creature in the process of casting a spell. You and the target both make an ability check with your respective spellcasting abilities. The target adds the level of the spell it is casting to its ability check, and you add the level at which you cast this counterspell to your ability check." + "\n " + "\u2022 If you know the spell the creature is attempting to cast or if you have it prepared you have advantage on this ability check, unless you are using this spell against another counterspell." + "\n " + "\u2022 If the result of your ability check is greater then the result of the target's ability check, its spell fails and has no effect.",
},

SpellsList["dire wail ll"] = {
    name : "Dire Wail LL",
    source : ["GMB:LL", 0],
    classes : ["bard", "shaman", "vessel"],
    level : 3,
    school : "Necro",
    time : "1 a",
    range : "Self(30-ft radius)",
    components : "V",
    duration : "1 min",
    description : "creatures of my choice in range make a con save. On fail, 4d10 thunder damage and deafened for duration. On succes, half damage and not deafened.",
    descriptionFull : "You let forth a wail filled with otherworldly power. Creatures of your choice within 30 feet must succeed on a Constitution saving throw or take 4d10 thunder damage and be deafened for the duration. At the end of each turn, targets can make a Constitution saving throw, ending the spell on a success. On a successful save, it takes half damage and is not deafened." + AtHigherLevels + "When you cast this spell using a spell slot of 4th-level or higher, the damage increases by 1d10 for each slot level above 3rd.",
},

SpellsList["flame arrow ll"] = {
    name : "Flame Arrow LL",
    source : ["GMB:LL", 0],
    classes : ["artificer", "druid", "magus", "ranger"],
    level : 3,
    school : "Trans",
    time : "1 bns",
    range : "Touch",
    components : "V,S",
    duration : "1 hour",
    description : "first 12 ranged attacks deal 1d6 bonus fire damage.",
    descriptionFull : "You touch a quiver containing ranged weapon ammunition. The first twelve pieces of ammunition drawn from the quiver deal fire damage in place of their normal damage type, plus an additional 1d6 fire damage on hit. If fired into a flammable object, it bursts into flame on hit. The magic of this spell ends for each piece of ammunition when it hits or misses, and the spell ends after twelve pieces of ammunition are fired." + AtHigherLevels + "When you cast this spell using a spell slot of 4th-level or higher, you can draw two additional pieces of ammunition from the quiver for each slot level above 3rd.",
},

SpellsList["hunger of hadar ll"] = {
    name : "Hunger of Hadar LL",
    source : ["GMB:LL", 0],
    classes : ["vessel", "warlock"],
    level : 3,
    school : "Conj",
    time : "1 a",
    range : "120-ft",
    components : "V,S,M",
    compMaterial : "pickled octopus tentacle",
    duration : "Conc, 1 min",
    description : "create a 20ft radius of darkness. Crea that start in it takes 2d6 cold damage. Crea that end in it must dex save or take 2d6 acid damage; +5ft radius and +1d6cold and +1d6 acid/SL",
    descriptionFull : "You open a gateway to the dark between the stars, a region infested with unknown horrors. A 20-foot-radius sphere of blackness and bitter cold appears, centered on a point with range and lasting for the duration. This void is filled with a cacophony of soft whispers and slurping noises that can be heard up to 30 feet away. No light, magical or otherwise, can illuminate the area, and creatures in the area are blinded." + "\n " + "\u2022 The void creates a warp in the fabric of space, and the area is difficult terrain. Any creature that starts its turn in the area takes 2d6 cold damage. Any creature that ends its turn in the area must succeed on a Dexterity saving throw or take 2d6 acid damage as milky, otherworldly tentacles rub against it." + AtHigherLevels + "When you cast this spell using a spell slot of 4th level or higher, the radius of the spell increases by 5 feet and both the cold and acid damage each increase by 1d6 for each slot level above 3rd.",
},

SpellsList["hypnotic pattern ll"] = {
    name : "Hypnotic Pattern LL",
    source : ["GMB:LL", 0],
    classes : ["bard", "psion", "sorcerer", "warlock", "wizard"],
    level : 3,
    school : "Illus",
    time : "1 a",
    range : "60-ft",
    components : "S,M",
    compMaterial : "a glowing stick of incense",
    duration : "Conc, 1 min",
    description : "30ft cube in radius. Each crea in area must wis save or be charmed for the duration. Charmed this way means incapacitated and 0 speed.",
    descriptionFull : "You create a twisting pattern of colors that weaves through the air inside a 30-foot cube within range. This psychedelic pattern appears for a moment and vanishes. Each creature in the area who sees the pattern must make a Wisdom saving throw. On a failed save, the creature becomes charmed for the duration. While charmed by this spell, the creature is incapacitated and has a speed of 0." + "\n " + "\u2022 An affected creature can repeat this saving throw at the end of each of its turns, ending the effect on a success. The spell also ends for an affected creature if it takes any damage or if someone else uses an action to shake it out of its stupor.",
},

SpellsList["irresistable dance ll"] = {
    name : "Irresistable Dance LL",
    source : ["GMB:LL", 0],
    classes : ["bard"],
    level : 3,
    school : "Ench",
    time : "1 a",
    range : "30-ft",
    components : "V",
    duration : "Conc, 1 min",
    description : "1 crea in range makes a wis save. On fail, it starts dancing, using all its movement to dance in place. Crea has dis. on dex saves and attack rolls.",
    descriptionFull : "You force a creature that can hear you within range to make a Wisdom saving throw. On a failure, it begins a comic dance in place: shuffling, tapping feet, and capering for the duration. Creatures that can't be charmed are immune to this spell." + "\n " + "\u2022 This creature must use all its movement to dance without leaving its space and has disadvantage on Dexterity saving throws and attack rolls. While the target is affected by this spell, creatures have advantage on attack rolls against it. As an action, a dancing creature makes a Wisdom saving throw to regain control of itself, ending the spell on a success." + AtHigherLevels + "When you cast this spell using a spell slot of 4th-level or higher, you target one additional creature who can hear you within range for each slot level above 3rd.",
},

SpellsList["lightning arrow ll"] = {
    name : "Lightning Arrow LL",
    source : ["GMB:LL", 0],
    classes : ["artificer", "ranger"],
    level : 3,
    school : "Trans",
    time : "1 attack",
    range : "Self",
    components : "V,S",
    duration : "Instantaneous",
    description : "shoot lightning as part of an attack. On hit, normal damage + 4d8 lightning damage. all within 10ft of target must dex save or 2d8 lightning damage + no reaction until beginning of my next turn. half damage on success; +1d8 on both effects/SL",
    descriptionFull : "As part of a ranged weapon attack, you can transmute a piece of ammunition, or the thrown weapon, into a bolt of lightning. On hit, the target takes the normal damage of the attack, plus a bonus 4d8 lighting damage. On a miss, the target takes half as much lightning damage, and none of the normal damage." + "\n " + "\u2022 Regardless if this attack hits or misses, all creatures within 10 feet of the target must make a Dexterity saving throw. On a failed save, creatures take 2d8 lighting damage, and half as much lighting damage on a success. The piece of ammunition or thrown weapon then returns to its normal form." + "\n " + "\u2022 Any creature that takes lighting damage from this spell cannot take reactions until the beginning of your next turn." + AtHigherLevels + "When you cast this spell using a spell slot of 4th-level or higher, the damage for both effects of the spell increases by 1d8 for each slot level above 3rd.",
},

SpellsList["sonic wave ll"] = {
    name : "Sonic Wave LL",
    source : ["GMB:LL", 0],
    classes : ["bard", "magus", "sorcerer"],
    level : 3,
    school : "Conj",
    time : "1 a",
    range : "Self(30-ft cone)",
    components : "V,S",
    duration : "Instantaneous",
    description : "all crea in cone must make con save or 4d8 thunder damage, fall prone, and deafened for 1 min. half damage and no prone/deafened on success.",
    descriptionFull : "You forcefully clasp your hands and a shockwave of booming force shoots forth from you and emits a boom audible out to 500 feet. All creatures in a 30-foot cone must succeed on a Constitution saving throw or take 4d8 thunder damage, fall prone, and be deafened for 1 minute. On a success, creatures take half damage and are not knocked prone or deafened." + "\n " + "\u2022 A creature can repeat this saving throw at the end of each of its turns, ending the effect on a success." + AtHigherLevels + "When you cast this spell using a spell slot of 4th-level or higher, the damage increases by 1d8, and the cone increases by 5 feet for each slot level above 3rd.",
},

SpellsList["spectral passage ll"] = {
    name : "Spectral Passage LL",
    source : ["GMB:LL", 0],
    classes : ["psion", "shaman", "sorcerer", "vessel", "warlock"],
    level : 3,
    school : "Trans",
    time : "1 a",
    range : "Touch",
    components : "V,S,M",
    compMaterial : "an object a spirit has passed through",
    duration : "Conc, 1 min",
    description : "crea becomes non-corporeal for the duration and can move through creatures/objects at half speed. ending inside an object/crea pushes you out, taking 1d10 force damage/5feet of travel.",
    descriptionFull : "You touch a willing creature. Until the spell ends, it becomes semi-incorporeal and can move through other creatures and objects as if they were difficult terrain. If the creature ends its movement inside another object or creature, it is immediately shunted to the nearest unoccupied space, taking 1d10 force damage for every 5 feet it was forced to travel." + AtHigherLevels + "When you cast this spell using a spell slot of 4th-level or higher, you can target one additional creature for each slot level above 3rd.",
},

SpellsList["tiny hut ll"] = {
    name : "Tiny Hut LL",
    source : ["GMB:LL", 0],
    classes : ["bard", "magus", "ranger", "shaman", "wizard"],
    ritual : true,
    level : 3,
    school : "Abjur",
    time : "1 min",
    range : "Self(10-ft hemisphere)",
    components : "V,S,M",
    compMaterial : "a pearl cut perfectly in half",
    duration : "8 hours",
    description : "create a dome for you and up to 9 other creatures. Crea inside during the casting can freely move in/out. Inside is a comfortable temperature/humidity.",
    descriptionFull : "A 10-foot-radius immobile dome of arcane force springs into existence around and above you and remains stationary for the duration. The spell ends if you leave its area." + "\n " + "\u2022 Nine creatures of Medium size or smaller can fit inside the dome with you. The spell fails if its area includes any Large creatures or more than nine creatures. Creatures and objects within the dome when you cast this spell can move through it freely. All other creatures and objects cannot pass through it. Spells and other magical effects cannot extend through the dome or be cast through it. The atmosphere inside the dome is comfortable and dry, regardless of the weather outside." + "\n " + "\u2022 Until the spell ends, you can command the interior to be dimly lit or dark. The dome is opaque and dull in color as to blend in with surroundings. It is transparent from the inside." + "\n " + "\u2022 Statistics: The dome has 100 hit points and Armor Class equal to your Spell save DC. It is immune to poison, psychic, and non-magical bludgeoning, piercing, and slashing damage, it is vulnerable to force and all magical bludgeoning, piercing, and slashing damage, and it is resistant to all other damage types. A disintegrate spell destroys it instantly.",
},

// 4th level

SpellsList["accursed touch ll"] = {
    name : "Accursed Touch LL",
    source : ["GMB:LL", 0],
    classes : ["druid", "cleric", "magus", "sorcerer", "warlock"],
    level : 4,
    school : "Trans",
    time : "1 a",
    range : "Touch",
    components : "V,S,M",
    compMaterial : "a basilisk scale",
    duration : "Conc, 1 min",
    description : "1 crea makes a con save. On fail, it starts to harden. If it saves 3 times after this it's free. If it fails 3 times it is petrified.",
    descriptionFull : "You attempt to transmute a creature into stone. As an action, you touch a creature, forcing it to make a Constitution saving throw. On a failed save, the creature is restrained as its flesh begins to harden. On a successful save, it isn't affected." + "\n " + "\u2022 A creature restrained by this spell must make another Constitution saving throw at the end of each of its turns. If it successfully saves against this spell three times, the spell ends. If it fails three saves, it is turned to stone and petrified. The successes and failures don't need to be consecutive; keep track of both until the creature fails or passes three saves." + "\n " + "\u2022 If the creature is physically broken while petrified, it suffers from similar deformities if it reverts to its original state." + "\n " + "\u2022 If you maintain your concentration for the entire duration, the creature is turned to stone until the effect is removed." + AtHigherLevels + "When you cast this spell using a spell slot of 5th level or higher, the number of saves it must fail before it is petrified is reduced by 1 (to a minimum of 1) for each level above 4th.",
},

SpellsList["eldritch tentacles ll"] = {
    name : "Eldritch Tentacles LL",
    source : ["GMB:LL", 0],
    classes : ["vessel", "warlock"],
    level : 4,
    school : "Conj",
    time : "1 a",
    range : "90-ft",
    components : "V,S,M",
    compMaterial : "a piece of tentacle from a giant squid",
    duration : "Conc, 1 min",
    description : "20ft square becomes difficult terrain. Crea that starts there or enters it must dex save or take 3d6 bludgeoning damage and be restrained until the spell ends.",
    descriptionFull : "Alien tentacles fill a 20-foot square on the ground you can see within range. For the duration, this area is difficult terrain." + "\n " + "\u2022 When a creature enters this area for the first time on a turn or starts its turn there, it must succeed on a Dexterity saving throw or take 3d6 bludgeoning damage and be restrained by the tentacles until the spell ends. Any creature that begins its turn in the area and is restrained by the tentacles takes 3d6 bludgeoning damage at the start of its turn." + "\n " + "\u2022 A creature restrained by the tentacles can use its action to make a Strength or Dexterity check (its choice) against your spell save DC. On a success, it frees itself from the tentacles." + AtHigherLevels + "When you cast this spell using a spell slot of 5th level or higher, both instances of damage from this spell increase by 1d6 for each slot level above 4th.",
},

SpellsList["ego scourge ll"] = {
    name : "Ego Scourge LL",
    source : ["GMB:LL", 0],
    classes : ["psion"],
    level : 4,
    school : "Ench",
    time : "1 a",
    range : "30-ft",
    components : "V",
    duration : "Conc, 1 min",
    description : "1 crea in choice makes an int save or has dis. on all attack rolls and ability checks and cannot cast spells.",
    descriptionFull : "You strike at the mind of a creature you can see within range, attacking its sense of self. It must succeed on an Intelligence saving throw or suffer disadvantage on attack rolls and ability checks, and be unable to cast spells for the duration." + "\n " + "\u2022 At the end of each of its turns the creature can repeat this saving throw, ending the effect of this spell on a success.",
},

SpellsList["polymorph ll"] = {
    name : "Polymorph LL",
    source : ["GMB:LL", 0],
    classes : ["druid", "magus", "sorcerer", "vessel", "warlock", "wizard"],
    level : 4,
    school : "Trans",
    time : "1 a",
    range : "30-ft",
    components : "V,S,M",
    compMaterial : "a caterpillar cocoon",
    duration : "Conc, 10 min",
    description : "transform 1 creature. Unwilling crea must succeed on a wis save to resist. shapechangers auto-save.",
    descriptionFull : "This spell transforms one creature you can see within range into a new form of your choice. An unwilling creature must succeed on a Wisdom saving throw to resist this effect, but shapechangers automatically succeed on their saving throw. This spell has no affect on a target that has 0 hit points. The transformation lasts for the duration, but it ends early if the target drops to 0 hit points or dies." + "\n " + "\u2022 Form. The new form can be any beast you have physically seen while it was living. It must have a Challenge Rating less than or equal to the target's level or its Challenge Rating." + "\n " + "\u2022 Statistics. Its game statistics, including its mental ability scores are replaced by those of the beast, but it does retain its alignment and personality within the limitations of that beast." + "\n " + "\u2022 The target assumes the hit points of its new form. When it reverts to its normal form, the creature returns to the number of hit points it had before it was transformed. If it reverts as a result of dropping to 0 hit points, any excess damage carries over to its normal form. If this excess damage reduces its normal form to 0 hit points, it is knocked unconscious." + "\n " + "\u2022 Actions. The actions the creature can take are limited to those its new form is able to perform. It cannot speak, cast spells, or take any actions that require hands or speech." + "\n " + "\u2022 Equipment. Its clothing, weapons, armor, and objects it is holding meld into the new form. However, it can't activate, use, wield, or otherwise benefit from any of its equipment.",
},

SpellsList["staggering smite ll"] = {
    name : "Staggering Smite LL",
    source : ["GMB:LL", 0],
    classes : ["paladin"],
    level : 4,
    school : "Evoc",
    time : "on hit",
    range : "Self",
    components : "V,M",
    compMaterial : "a melee weapon worth at least 1 sp",
    duration : "Instantaneous",
    description : "on hit with melee weapon, target takes an additional 4d6 psychic damage and must wis save or or has dis. on attack rolls and ability checks and cannot take reactions.",
    descriptionFull : "When you hit with a melee weapon attack you can cause the weapon to pierce both body and mind. This attack deals 4d6 additional psychic damage, and the target must succeed on a Wisdom saving throw or until the start of its next turn, it has disadvantage on attack rolls and ability checks and it cannot take reactions." + "\n " + "\u2022 If your target is an aberration or it can speak telepathically this bonus psychic damage increases by 1d6." + AtHigherLevels + "When you cast this spell using a spell slot of 5th-level or higher, the psychic damage increases by 1d6 for each spell slot level above 4th.",
},

// 5th level

SpellsList["banishing smite ll"] = {
    name : "Banishing Smite LL",
    source : ["GMB:LL", 0],
    classes : ["paladin"],
    level : 5,
    school : "Evoc",
    time : "on hit",
    range : "Self",
    components : "V,M",
    compMaterial : "a melee weapon worth at least 1 sp",
    duration : "Conc, 1 min",
    description : "on hit with melee weapon, target takes an additional 5d10 force damage, and if it reduces target to less than 50hp they are banished.",
    descriptionFull : "When you hit with a melee weapon attack you can cause the weapon to crackle with pure arcane force. This attack deals 5d10 bonus force damage, and if it reduces the target to 50 hit points or fewer, it is banished from the current plane." + "\n " + "\u2022 If the target is native to a different plant of existence than the one you are currently on, it disappears, returning to its home plane. If the target is native to your current plane, it is banished to a harmless demiplane where it is incapacitated. When the spell ends, the target returns to the space it was banished from, or the nearest unoccupied space." + "\n " + "\u2022 If the target is not native to your current plane of existence this bonus force damage increases by 1d10." + AtHigherLevels + "When you cast this spell using a spell slot of 6th-level or higher, the bonus force damage increases by 1d10 for each spell slot level above 5th.",
},

SpellsList["psychic crush ll"] = {
    name : "Psychic Crush LL",
    source : ["GMB:LL", 0],
    classes : ["psion"],
    level : 5,
    school : "Evoc",
    time : "1 a",
    range : "90-ft",
    components : "V",
    duration : "Conc, 1 min",
    description : "1 crea in range must str save or take 5d8 force damage. on fail, crea must repeat saving throw each turn or take 2d8 until succeeded.",
    descriptionFull : "You exert the full force of your will upon a creature you can see within range. It must succeed on a Strength saving throw, taking 5d8 force damage on a failure and half as much force damage on a success. It must repeat this saving throw at the end of each of its turns, taking 2d8 force damage on a failure, and ending the effects of this spell on a success." + "\n " + "\u2022 If this spell reduces a creature to 0 hit points it is crushed into a flesh-colored ball, roughly the size of your fist." + AtHigherLevels + "When you cast this spell using a spell slot of 6th-level or higher, each instance of force damage it deals increases by 1d8 for each spell slot level above 5th.",
},

SpellsList["spiritual sunder ll"] = {
    name : "Spiritual Sundering LL",
    source : ["GMB:LL", 0],
    classes : ["cleric", "shaman", "warlock"],
    level : 5,
    school : "Ench",
    time : "1 a",
    range : "120-ft",
    components : "V,S",
    duration : "Instantaneous",
    description : "creatures in 20ft radius of point in range must cha save or take 8d6 necrotic damage and subtract 1d6 from all int/wis/cha saves for 1 min.",
    descriptionFull : "Creatures in a 20-foot-radius sphere centered on a point of your choice within range have their soul rent, and must make a Charisma saving throw. On a failure, they take 8d6 necrotic damage, and for the next minute, they have a muddied sense of self and subtract 1d6 from any Intelligence, Wisdom, or Charisma saving throw they make. On a success, they take half damage and suffer no saving throw penalty." + "\n " + "\u2022 Targets can make a Charisma saving throw at the end of each of their turns, ending the effect on a successful save.",
},

SpellsList["steel wind strike ll"] = {
    name : "Steel Wind Strike LL",
    source : ["GMB:LL", 0],
    classes : ["magus", "ranger"],
    level : 5,
    school : "Conj",
    time : "1 a",
    range : "30-ft",
    components : "V,M",
    compMaterial : "a melee weapon worth at least 1 sp",
    duration : "Instantaneous",
    description : "make an attack against up to 5 crea in range. On hit, they take 5d10 force damage + the normal weapon damage.",
    descriptionFull : "You flourish the weapon used in the casting and then vanish to strike like the wind. Choose up to five targets you can see within range. Make one melee weapon attack against each target using the weapon used in the casting. On a hit, targets take the normal damage of an attack with that weapon plus an additional 5d10 force damage." + "\n " + "\u2022 You can then teleport to an unoccupied space you can see within 5 feet of one of the targets you hit or missed.",
},

SpellsList["swift quiver ll"] = {
    name : "Swift Quiver LL",
    source : ["GMB:LL", 0],
    classes : ["ranger"],
    level : 5,
    school : "Trans",
    time : "1 bns",
    range : "Touch",
    components : "V,S,M",
    compMaterial : "a quiver with a piece of ammunition",
    duration : "Conc, 1 min",
    description : "For the duration, you can use your bonus action to make 2 ranged attacks.",
    descriptionFull : "You transmute your quiver so it produces an endless supply of nonmagical ammunition, which seems to leap into your hand when you reach for it." + "\n " + "\u2022 On each of your turns until the spell ends, you can use a bonus action (including the bonus action used to cast this spell) to make two attacks with a ranged weapon that uses ammunition from this quiver. When you make such a ranged attack, your quiver magically replaces the ammunition you used with a nonmagical copy of that ammunition. Pieces of ammunition created by this spell disintegrate when the spell ends. If the quiver leaves your possession, the spell ends.",
},

SpellsList["vorpal blade ll"] = {
    name : "Vorpal Blade LL",
    source : ["GMB:LL", 0],
    classes : ["magus", "paladin"],
    level : 5,
    school : "Trans",
    time : "1 attack",
    range : "Touch",
    components : "V,S,M",
    compMaterial : "the finger bone of a necromancer",
    duration : "Instantaneous",
    description : "1 melee spell attack. On hit, 6d8+SpellMod force damage. If this reduces a creature to less than 50hp, I cut off one of their heads.",
    descriptionFull : "You conjure a blade of pure negative energy in your empty hand and make one melee weapon attack against a creature within your reach, attempting to behead it. On hit, it takes force damage equal to 6d8 + your spellcasting modifier." + "\n " + "\u2022 If this damage reduces the creature to 50 hit points or fewer, you instantly cut off one of its heads of your choice." + "\n " + "\u2022 The creature instantly dies if it cannot survive without the lost head. The creature's head is not removed if it is immune to slashing damage, or if it doesn't have or need a head.",
},

SpellsList["wall of force ll"] = {
    name : "Wall of Force LL",
    source : ["GMB:LL", 0],
    classes : ["magus", "psion", "sorcerer", "wizard"],
    level : 5,
    school : "Abjur",
    time : "1 a",
    range : "60-ft",
    components : "V,S,M",
    compMaterial : "powder from crushed clear gemstone",
    duration : "Conc, 10 min",
    description : "Conjure wall of force that extends through the Ethereal Plane (see full spell).",
    descriptionFull : "A shimmering opaque wall of force springs into existence at a point you choose within range and lasts for the duration." + "\n " + "\u2022 Orientation & Shape. The wall appears in any orientation you choose, as a horizontal or vertical barrier or an angle. It can be free floating or rest on a solid surface. You can form it into a hemispherical dome, a sphere with a radius of up to 10 feet, or you can shape a flat surface made up of ten 10-by-10-foot panels. Each panel must be contiguous with another. In any form, the wall is 1/4 inch thick. Nothing can pass through the wall physically, and anything viewed through it is lightly obscured. The wall extends into the Ethereal Plane, blocking ethereal travel through the wall. If it cuts through a creature's space when it appears, the creatures must make a Dexterity saving throw. On a success, it chooses which side of the wall it moves to. On a failure, you choose the side it moves to." + "\n " + "\u2022 Statistics. The wall has 150 hit points and its Armor Class equals your Spell save DC. It is immune to poison, psychic, and non-magical bludgeoning, piercing, and slashing damage, vulnerable to force and magical bludgeoning, piercing, and slashing damage, and resistant to all other damage types. It cannot be dispelled by a dispel magic spell, but a disintegrate spell destroys the wall it instantly." + AtHigherLevels + "When you cast this spell using a spell slot of 6th-level or higher, the hit points of the wall created by this spell increase by 25 for each spell slot level above 5th.",
},

// 6th level

SpellsList["psionic oppression ll"] = {
    name : "Psionic Oppresion LL",
    source : ["GMB:LL", 0],
    classes : ["psion"],
    level : 6,
    school : "Ench",
    time : "1 a",
    range : "60-ft",
    components : "V,S",
    duration : "1 min",
    description : "1 crea in range must int save or take 12d6 psychic damage and be stunned for 1 min. Half damage and not stunned on save.",
    descriptionFull : "You psionically overwhelm the mind of one creature you can see within range. It must succeed on an Intelligence saving throw or it takes 12d6 psychic damage and is stunned for 1 minute. On a successful save, the target takes half as much psychic damage and is not stunned." + "\n " + "\u2022 The stunned target can repeat the saving throw at the end of each of its turns, ending the effect on a success.",
},

// 7th level

SpellsList["forcecage ll"] = {
    name : "Forcecage LL",
    source : ["GMB:LL", 0],
    classes : ["psion", "warlock", "wizard"],
    level : 7,
    school : "Conj",
    time : "1 a",
    range : "60-ft",
    components : "V,S,M",
    compMaterial : "an ornate jade box worth 1,500 gp",
    duration : "Conc, 1 hour",
    description : "conjure a cube shaped prison of magical force (see full spell).",
    descriptionFull : "A shimmering, immobile, cube-shaped prison composed of magical force springs into existence around an area of your choice within range. You choose whether this magic prison is shaped like a cage with bars or a solid box." + "\n " + "\u2022 Shape. If you choose cage, it can be up to 20 feet on a side and made from 1/2-inch diameter bars spaced 1/2 inch apart. If you choose box, it can be up to 10 feet on a side, creating a solid barrier that prevents any matter from passing through it and blocking any spells cast into or out of the area. The cage extends into the Ethereal Plane, blocking ethereal travel." + "\n " + "\u2022 Creatures Inside. When you cast the spell, any creatures that are completely inside the area of the cage are trapped. Any creatures partially within the area, or too large to fit are pushed away until they are completely outside of the cage." + "\n " + "\u2022 A creature inside the cage cannot leave it by non-magical means. If the creature tries to use teleportation or interplanar travel to leave the cage, it must first make a Charisma saving throw. The spell or effect is wasted on a failed save, but on a success the creature uses the spell or effect to escape." + "\n " + "\u2022 Statistics. The cage's Armor Class equals your Spell save DC and it has 200 hit points. It is immune to poison, psychic, and non-magical bludgeoning, piercing, and slashing damage, vulnerable to force and magical bludgeoning, piercing, and slashing damage, and resistant to all other damage types. It cannot be dispelled by a dispel magic spell, but a disintegrate spell destroys the cage it instantly." + AtHigherLevels + "When you cast this spell using a spell slot of 8th-level or higher, the hit points of the cage created by this spell increase by 25 for each spell slot level above 7th.",
},

// 8th level

SpellsList["mass polymorph ll"] = {
    name : "Mass Polymorph LL",
    source : ["GMB:LL", 0],
    classes : ["sorcerer", "wizard"],
    level : 8,
    school : "Trans",
    time : "1 a",
    range : "30-ft",
    components : "V,S,M",
    compMaterial : "a caterpillar cocoon for each target",
    duration : "Conc, 10 min",
    description : "cast polymorph on up to 5 creatures in range. Unwilling creatures must succeed on a wis save. (see full spell)",
    descriptionFull : "This spell transforms up to five creatures you can see within range into a new form of your choice, and you can choose the same or different forms for each target. An unwilling creature must succeed on a Wisdom saving throw to resist this effect. Shapechangers automatically succeed on their saving throw. This spell has no affect on a target that has 0 hit points. The transformation lasts for the duration, but it ends early if the target drops to 0 hit points or dies." + "\n " + "\u2022 Form. The new form can be any beast you have physically seen while it was living. It must have a Challenge Rating less than or equal to the target's level or its Challenge Rating." + "\n " + "\u2022 Statistics. Its game statistics, including its mental ability scores are replaced by those of the beast, but it does retain its alignment and personality within the limitations of that beast." + "\n " + "\u2022 The target assumes the hit points of its new form. When it reverts to its normal form, the creature returns to the number of hit points it had before it was transformed. If it reverts as a result of dropping to 0 hit points, any excess damage carries over to its normal form. If this excess damage reduces its normal form to 0 hit points, it is knocked unconscious." + "\n " + "\u2022 Actions. The actions the creature can take are limited to those its new form is able to perform. It cannot speak, cast spells, or take any actions that require hands or speech." + "\n " + "\u2022 Equipment. Its clothing, weapons, armor, and objects it is holding meld into the new form. However, it can't activate, use, wield, or otherwise benefit from any of its equipment." + AtHigherLevels + "If you cast this spell using a 9th-level spell slot, you can target up to 10 creatures within range.",
},

// 9th level

SpellsList["weird ll"] = {
    name : "Weird LL",
    source : ["GMB:LL", 0],
    classes : ["psion", "warlock", "wizard"],
    level : 9,
    school : "Ench",
    time : "1 a",
    range : "120-ft",
    components : "V,S",
    duration : "Conc, 1 min",
    description : "cast polymorph on up to 5 creatures in range. Unwilling creatures must succeed on a wis save. (see full spell)",
    descriptionFull : "Drawing on the deepest fears, regrets, and primal instincts of a creature, you create the illusion of the most horrifying thing imaginable to them, which is visible only to that creature." + "\n " + "\u2022 Choose a point within range, and creatures of your choice within a 30-foot radius of the point become frightened for the duration. If a target is immune to the frightened condition, it must make a Wisdom saving throw or be frightened anyway." + "\n " + "\u2022 At the end of each of a frightened creature's turns, it must succeed on a Wisdom saving throw or it takes 4d10 psychic damage. On a success, the spell ends for that target.",
}